name: May Helena Plumb
description: May Helena Plumb is a linguist who studies Zapotec languages.
url: http://www.mayhplumb.com
#permalink: /:categories/:year/:month/:day/:title/
permalink: pretty
excerpt_separator: <!--excerpt-->

plugins:
  - jekyll-paginate-v2
  - jekyll-feed

pagination:
  enabled: true
  collection: 'posts'
  per_page: 6
  title: ':title - Page :num'
  sort_reverse: true
