name: May Helena Plumb
description: May Helena Plumb is a linguist who studies Zapotec languages.
url: http://www.mayhplumb.com
permalink: /:year/:month/:day/:title/
excerpt_separator: <!--exerpt-->

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  collection: 'posts'
  per_page: 2
  title: ':title - Page :num'
  sort_reverse: true